### ISSUE TITLE
Key import failed

### ISSUE THREAD

**Issue by ThatOneCalculator** [ouchadam/small-talk#110]
After exporting the room keys from Element and entering the password, it fails

**Comment by ouchadam** [comment]
Thanks for raising! To double check, which client did you use to export the keys? I'll try the same steps

**Comment by ThatOneCalculator** [comment]
Element web :)

**Comment by ouchadam** [comment]
I've not been able to reproduce the issue on my side 🤔  I've logged into a large ish~ account, a 30mb export from web, it takes about 60-90 seconds to import into small-talk (which is quite slowly) but the import works.

The error handling is lacking in this area, I'll look to improve the experience (actual error messages and speed up the import)

**Comment by ThatOneCalculator** [comment]
I might be exporting the wrong thing... what exact steps should I take to get a proper export?

**Comment by ouchadam** [comment]
There are quite a lot of security/crypto options in Element 😅 

The import in SmallTalk only works with the E2E room keys, in Element web these can be found at... Settings -> Security & Privacy -> Cryptography -> `Export E2E room keys`

<img width="652" alt="Screenshot 2022-09-04 at 14 31 06" src="https://user-images.githubusercontent.com/1848238/188316208-c42cc8b0-9d52-43f1-ab3c-ecd3149add4c.png">

the automatic release later today will include several improvements to the key importing https://github.com/ouchadam/small-talk/pull/117 I'm hoping it'll be able to provide more information into your issue

**Comment by ouchadam** [comment]
:wave: checking in, were you able to get the key imports to work in the end?

**Comment by ThatOneCalculator** [comment]
Sorry about that, it works now :)

![Screenshot_20220912-135029.png](https://user-images.githubusercontent.com/44733677/189756107-cb93ba2b-5a86-4043-8274-45bde47522a0.png)

**Comment by ouchadam** [comment]
:raised_hands:  great to hear!
