### ISSUE TITLE
Google Translate Service

### ISSUE THREAD

**Issue by AnisTaluqdar** [ouchadam/small-talk#121]
If you can add the Google Translate service it will be amazing as https://imem.app/ they add for telegram client. 

It's really helpful when it comes to chatting with outside the world who don't know English.

**Comment by ouchadam** [comment]
Thanks for the suggestion! My plan is to keep the base SmallTalk as lean as possible, this feature might be better suited as a bot, applet or Google lens

**Comment by ThatOneCalculator** [comment]
I agree. Google Translate is also a non-free service, so if something *were* to be implemented like this, it should request something like the LibreTranslate API rather than talking directly to Google, but it'd be best to handle translations outside of the app.
