### ISSUE TITLE
Light mode

### ISSUE THREAD

**Issue by ThatOneCalculator** [ouchadam/small-talk#135]
In app:

![Screenshot_20220908-121934.png](https://user-images.githubusercontent.com/44733677/189207870-169fa87e-049e-488d-87f6-7531a8c21233.png)

Home screen (device is in light mode):

![Screenshot_20220908-121928.png](https://user-images.githubusercontent.com/44733677/189207923-53adbe51-5aba-4b64-87ab-877b3eef02c4.png)

**Comment by ouchadam** [comment]
From the image there's a slight orange tint to the background which comes from the dark dynamic colour scheme (Material You), at the moment only dark schemes are supported 

Do you have any examples of other apps making use of the wallpaper background providing a different  colour? (So I can check locally as well)

**Comment by ThatOneCalculator** [comment]
Ah you're right, it was a bit hard to notice since I pretty much only use light mode.

**Comment by ouchadam** [comment]
added a light theme via #139
