### ISSUE TITLE
Application crashes right after first trying to sign-on

### ISSUE THREAD

**Issue by mi5o** [ouchadam/small-talk#147]
**version:** 08/09/2022-V1, from IzzyOnDroid repo
**OS:** Android 10 / LineageOS 17.1, no framework or services from Google available at OS level
**issue:** application crash

**steps to reproduce:**
- option 1: install app, launch it, enter correct login and password, submit;
- option 2: install app, launch it, enter correct login and password, submit, ignore application crash, try to launch it again;

expected outcome: buddies roster displayed
observed outcome: application fatal crash

(Both options works for me, I can reliably achieve the same outcome repeatedly.)

**excerpt from logcat:**
09-17 15:16:42.404 18550 18550 E AndroidRuntime: FATAL EXCEPTION: main
09-17 15:16:42.404 18550 18550 E AndroidRuntime: Process: app.dapk.st, PID: 18550
09-17 15:16:42.404 18550 18550 E AndroidRuntime: java.lang.IllegalArgumentException: Shortcut must have a non-empty label
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at c3.a0.f(SourceFile:28)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at c3.a0.X(SourceFile:2)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at c8.z.b(SourceFile:2)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at t.y0.W0(SourceFile:7)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at c8.k.f(Unknown Source:11)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at j7.a.A(Unknown Source:8)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at z7.k0.run(Unknown Source:86)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at z7.v0.e0(SourceFile:3)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at z7.l.o(SourceFile:3)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at b8.b.e(Unknown Source:6)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at b8.k.k(SourceFile:2)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at b8.j.h(Unknown Source:0)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at d8.u.b(Unknown Source:68)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at c3.s.b(SourceFile:30)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at w5.d.b(SourceFile:1)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at w5.c.f(Unknown Source:12)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at j7.a.A(Unknown Source:8)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at z7.k0.run(Unknown Source:86)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
09-17 15:16:42.404 18550 18550 E AndroidRuntime: 	Suppressed: k5.e: [y1{Cancelling}@833d402, Dispatchers.Main.immediate]
09-17 15:16:42.407  5644 10438 W ActivityTaskManager:   Force finishing activity app.dapk.st/.MainActivity
09-17 15:16:42.408  5644 18673 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
09-17 15:16:42.423  5644  5672 I ActivityManager: Showing crash dialog for package app.dapk.st u0
09-17 15:16:42.423  5644  5672 E system_server: Invalid ID 0x00000000.

**other notes:** From what I could deduce from logcat, the sign-on was successful. The above mentioned error has occurred during HTTP request to  https://matrix-client.matrix.org/_matrix/client/r0/sync?since=s(privacy-protected)&filter=24&timeout=30000, but it seems unrelated.

**Comment by ouchadam** [comment]
thanks for raising and providing the crash log!  `IllegalArgumentException: Shortcut must have a non-empty label`, looks like  `ST` is unable to read / generate a room name. Should be an easy fix 🤞 

Out of interest does your account make use of Matrix spaces?

**Comment by mi5o** [comment]
Glad to help any bona fide FOSS developer :clap:

As for room names, I am intentionally not filling room names. I am using private encrypted chat rooms running for years, either in one-to-one setup or just a few people. Then, naming the room is counterproductive. Instead, implied room names are much more useful. For example, if I am Adam and I am in a private room with Bob and Claire, the best room name for me is "_Bob, Claire_", while for Claire it is "_Adam, Bob_."

I am not sure whether I understand your question. Is it some attribute of an account? I found no such settings in my client app. If you meant whether I use spaces, I think I do not. Once in the past, some Matrix client was asking me whether I want to try out something new (maybe it was spaces), I consented, so it might have changed something somewhere, but later I forgot about it.

**Comment by ouchadam** [comment]
ah unnamed rooms is a use case I hadn't properly handled yet and is specified in the matrix spec through the use of `Heroes`
https://spec.matrix.org/unstable/client-server-api/#calculating-the-display-name-for-a-room

will be fixed by https://github.com/ouchadam/small-talk/pull/149 (I also took the opportunity to ensure room names can't be blank)

> I am not sure whether I understand your question. Is it some attribute of an account

sorry, I meant [these spaces](https://element.io/blog/spaces-the-next-frontier/) as it's another area where ST may act unexpectedly~

**Comment by mi5o** [comment]
Wow, there is a spec for a use-case with unnamed rooms. Kudos to authors.

Looking forward to test the app for the first time :slightly_smiling_face:

I knew that you had this Matrix feature on your mind. I just was not sure whether it is something you need to opt-in first, and only then you can use it, or it is something you can either use or not use, anytime you want. Anyway, I have not set up any spaces yet.

**Comment by ouchadam** [comment]
fixed in https://github.com/ouchadam/small-talk/releases/tag/19%2F09%2F2022-V1 :tada:

**Comment by mi5o** [comment]
affirmative
