### ISSUE TITLE
Attach images/files

### ISSUE THREAD

**Issue by ThatOneCalculator** [ouchadam/small-talk#148]
Pretty self explanatory, basically the only thing preventing me from daily-driving ST at this point

**Comment by ouchadam** [comment]
💯  I'm really keen to add this, at the moment ST _sort of_ supports sharing images (eg opening a gallery app -> share -> selecting ST) but they're not encrypted and from my testing some bridges, like whatsapp aren't working correctly with the images 

Relevant tickets~

Encrypt images https://github.com/ouchadam/small-talk-features/issues/1
Add a image picker/gallery https://github.com/ouchadam/small-talk-features/issues/2

I'm going to close this in favour of the above tickets ^^^ (I'm trialing splitting the features/wishlist/roadmap issues into a separate repository, leaving bugs/crashes/help in the main repo)
