### ISSUE TITLE
Name collision with a classic programming language

### ISSUE THREAD

**Issue by McSinyx** [ouchadam/small-talk#173]
While the app is still under development, I suggest rename it to something else to avoid confusion.

**Comment by ouchadam** [comment]
thanks for raising, I would challenge this with a candid question, did the project name cause you confusion?

I consider the following reasons for not changing the name

- The programming language is niche
- The programming language doesn't have mass appeal and is unlikely to see a resurgence (despite a vast legacy)
- Different audiences, one targeting enterprise professionals, the other consumers
- Different contexts, one being a programming language, the other a mobile application
- Name collisions can co exists (eg matrix)
