### ISSUE TITLE
an issue for my sp.codes account....

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [ouchadam/small-talk#189]
**I have managed to log in with my Samsung S21 5G. That didn't work until now. 
Attached are 2 pictures of how it currently looks.
You can currently write in the rooms you entered with another client.
Nothing else works yet.
But - I am one step further than before. So much for the current status.**
![photo1665077497](https://user-images.githubusercontent.com/61406324/194381638-78121fc8-fa7b-4993-a396-77210c11d867.jpeg)
![photo1665077529](https://user-images.githubusercontent.com/61406324/194381643-7a8f20f4-14ac-43b0-8b2c-5c422be4dc52.jpeg)

**Comment by ouchadam** [comment]
Great to see it working! 

Showing the rooms list and being able to send messages/images (encrypted if supported by the room) is the majority of the current feature set

At the moment `SmallTalk` doesn't fetch room history https://github.com/ouchadam/small-talk-features/issues/10

**Comment by ouchadam** [comment]
going to close as the lack of room history is a known missing feature
