### ISSUE TITLE
Can't import room keys

### ISSUE THREAD

**Issue by ThatOneCalculator** [ouchadam/small-talk#195]
This is after entering the password

![Screenshot_20221008-130304.png](https://user-images.githubusercontent.com/44733677/194725941-1b4f2674-c581-4ab5-a93e-29481dcfec57.png)

**Comment by ouchadam** [comment]
thanks for providing the screenshot :+1:  which client was used to export the keys and does the file correctly import into other matrix clients?

this error sounds like the file used doesn't contain enough information in the first line :thinking: here's an example keys file used for testing https://github.com/ouchadam/small-talk/blob/main/test-harness/src/test/resources/element-keys.txt notice how after the `-----BEGIN MEGOLM SESSION DATA-----` all lines are 129 characters long

Currently the code takes the first 36 bytes from the first line of the file as the _crypto cipher_, the error you're seeing means that the first line doesn't contain at least 36 bytes of data (assuming the error is referring to this line https://github.com/ouchadam/small-talk/blob/main/matrix/services/crypto/src/main/kotlin/app/dapk/st/matrix/crypto/internal/RoomKeyImporter.kt#L110 )

**Comment by ouchadam** [comment]
without more information about the file being imported this will be tricky to resolve, will reopen when more information becomes available

**Comment by ThatOneCalculator** [comment]
Oh shoot sorry... It was from Element web
