### ISSUE TITLE
Decrypted messages are replaced with encrypted versions

### ISSUE THREAD

**Issue by ouchadam** [ouchadam/small-talk#205]
> The first time I've imported encryption keys from a file, it has decrypted successfully the messages. Then at the first message received, previous decrypted message lost their keys and appeared as encrypted. Then I've imported it again, close the app and the message are correctly decrypted even if I receive a message

https://github.com/ouchadam/small-talk/issues/199

**Comment by ouchadam** [comment]
this was likely caused by https://github.com/ouchadam/small-talk/pull/208, have been unable to reproduce locally

**Comment by octoshrimpy** [comment]
I just had this happen to me in `31/10/2022-V1-fdroid`
