### ISSUE TITLE
Infinite loading when trying to sign into account on a Dendrite server 

### ISSUE THREAD

**Issue by ThatOneCalculator** [ouchadam/small-talk#212]
v17/10/2022-V1 FOSS Signed

**Comment by ouchadam** [comment]
thanks for the heads up! I haven't tried out dendrite yet

**Comment by ThatOneCalculator** [comment]
I have a server that you can register on to test it: `youre-s.us` (the website doesn't have any UI so you just have to sign up on element/etc)

**Comment by ouchadam** [comment]
awesome, I'll give it a go :crossed_fingers:

**Comment by ouchadam** [comment]
Found the problem  (assuming there isn't more...), dendrite seems to allow the `device_one_time_keys_count`  to be optional whereas synapse always provides it 

```
19:09:36.874  W  Caused by: kotlinx.serialization.MissingFieldException: Field 'device_one_time_keys_count' is required for type with serial name 'app.dapk.st.matrix.sync.internal.request.ApiSyncResponse', but it was missing at path: $
19:09:36.874  W  	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:90)
19:09:36.874  W  	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:95)
19:09:36.874  W  	at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:71)
19:09:36.875  W  	... 43 more
```

**Comment by ouchadam** [comment]
Allowing the field to be optional until it's provided does the trick

| ST PROFILE | ST CHAT | ELEMENT CHAT |
| --- | --- | --- |
![Screenshot_20221022_191305](https://user-images.githubusercontent.com/1848238/197356409-918aa7ae-feed-4100-ae58-c67d16cc0d0a.png)|![Screenshot_20221022_191336](https://user-images.githubusercontent.com/1848238/197356408-dd1503cc-a84d-471f-879b-62ea1ff96eca.png)|![2022-10-22T19:14:11,907131247+01:00](https://user-images.githubusercontent.com/1848238/197356407-0cb1a55b-ccbc-4759-9b9a-fc3e6250422c.png)

**Comment by ouchadam** [comment]
fixed by #218

**Comment by ThatOneCalculator** [comment]
Thank you for fixing it so fast! Apparently Conduit has this same behavior, so I guess that added compatibility there too!

**Comment by ouchadam** [comment]
:raised_hands:  

unfortunately these types of problems are trial and error, the spec doesn't clearly define if these fields are optional or not https://spec.matrix.org/v1.3/client-server-api/#get_matrixclientv3sync :cry:

**Comment by theotheroracle** [comment]
so to clarify, this fixes conduit not working and i shouldn't open a bug for that ?

**Comment by ThatOneCalculator** [comment]
It should but I haven't fully tested conduit so if youre having issues you should open a new issue

**Comment by theotheroracle** [comment]
was this merged into the latest release or should i wait for the next release

**Comment by ThatOneCalculator** [comment]
It's in the latest.
