### ISSUE TITLE
can't see anonymousland.org

### ISSUE THREAD

**Issue by Wjxfi** [ouchadam/small-talk#226]
I can't log in to my account

**Comment by ouchadam** [comment]
`anonymousland.org` doesn't host a wellknown on their domain, which means `SmallTalk` can't do an automatic lookup, instead you'll need to provide the matrix server url manually

notice https://www.anonymousland.org/.well-known/matrix/client 404's compared to https://www.matrix.org/.well-known/matrix/client

I can sign in by providing the matrix server address `matrix.anonymousland.org`, the option is displayed when SmallTalk detects no hosted `wellknown` 

<img src="https://user-images.githubusercontent.com/1848238/198898358-ad4dc9ba-30cd-4445-bbf7-7f507c2a53dd.png" height="800">
