### ISSUE TITLE
Buggy hypertext handling

### ISSUE THREAD

**Issue by mi5o** [ouchadam/small-talk#237]
The application handles hypertext well, but there are glitches here and there.

## Example 1

Original message: `<p>text</p>\n<ul>\n<li>text apparent-url text <strong>text</strong> text</li>\n<li>text apparent-url text<strong>text</strong> text</li>\n<li>text apparent-url text &quot;text&quot; text <strong>text</strong> text</li>\n</ul>\n`

Displayed as (notice correct `strong` tag handling, correctly detected URLs in plain text, and ignored `ul` and `li` tags):

> text
> 
> &lt;ul>
> &lt;li>text [apparent-url](https://example.com/) text **text** text&lt;/li>
> &lt;li>text [apparent-url](https://example.com/) text **text** text&lt;/li>
> &lt;li>text "text" text [apparent-url](https://example.com/) text **text** text&lt;/li>
> &lt;/ul>

## Example 2

original message: `text-&gt;text`

displayed as (ignored `>` reference):

> text-&amp;gt;text

## Example 3

original message: `\n<h3>text</h3>\n\n<p>text</p>\n\n<p>text<a href="https://example.com">text</a>text<a href="https://example.com">text</a>text</p>\n\n<p>text<strong>text</strong>text</p>\n\n<p><strong>text</strong>text&#39;text</p>\n\n<p><strong>text</strong>\ntext<a href="https://example.com">text</a>text\ntext&#39;text</p>\n\n<p>text<a href="https://example.com">apparent-url</a>text<a href="https://example.com">apparent-url</a>text</p>\n`

displayed as (notice three different styles of detecting/handling links, correct handling of `'` reference, and no handling of `strong` and `p` tags):

> **text**
> 
> &lt;p>text&lt;/p>
> &lt;p>text &lt;a href="[https://example.com">te](https://example.com">te)xt&lt;/a> text &lt;a href="[https://example.com">te](https://example.com">te)xt&lt;/a>text&lt;/p>
> &lt;p>text&lt;strong>text&lt;/strong>text&lt;/p>
> &lt;p>&lt;strong>text&lt;/strong>text'text&lt;/p>
> &lt;p>&lt;strong>text&lt;/strong> text &lt;a href="[https://example.com">te](https://example.com">te)xt&lt;/a>text text'text&lt;/p>
> &lt;p>text &lt;a href="[https://example.com">apparent-url&lt;/a](https://example.com">apparent-url&lt;/a)> text [apparent-url](https://example.com) text&lt;/p>

----

(seen in foss-signed-31.10.2022-V1.apk running in LineageOS)

**Comment by ouchadam** [comment]
thanks for the examples! :100:
