### ISSUE TITLE
Modified messages displayed out of their original order

### ISSUE THREAD

**Issue by mi5o** [ouchadam/small-talk#240]
Modified messages appear (almost) correctly modified, but out of their original order.

**Steps to reproduce:**
1. send message 1
2. send message 2
3. send message 3
4. modify message 2 to message 2+

**Expected result:**
> Message 1 [HH:MM]
> Message 2+ [edited HH:MM]
> Message 3 [HH:MM]

**Actual result:**
> Message 1 [HH:MM]
> Message 3 [HH:MM]
> \* Message2+ [edited HH:MM]

Also note the redundant asterisk at the beginning of the modified message – it already clearly indicates it has been modified.

(seen in foss-signed-31.10.2022-V1.apk running in LineageOS)

**Comment by ouchadam** [comment]
can confirm :+1:  seems to happen when editing your own messages from another client, when others edit their messages it's working as expected (at least for me!)

**Comment by ouchadam** [comment]
fixed by https://github.com/ouchadam/small-talk/pull/246 (the asterisk has also been removed in recent commits)

**Comment by mi5o** [comment]
>  seems to happen when editing your own messages from another client,

I have not seen the fix yet, so maybe it works as expected. But I am going to challenge your description of the cause.

I did everything at one device, in one app (Matrix for Android), in one chat room, as one user, immediately one step after another, editing my own messages in one client.

**Comment by ouchadam** [comment]
ah when checking messages from others I may have originally only been trying to edit the latest message, the fix from above will cover both cases
