### ISSUE TITLE
emoji verification half implemented ?

### ISSUE THREAD

**Issue by theotheroracle** [ouchadam/small-talk#266]
when trying to verify from another client, it recognizes that smalltalk supports emoji verification, and it even generates an emojicode, but smalltalk doesnt render anything, which is incorrect behaviour . it shouldnt accept an emoji verification request until support is finished

**Comment by ouchadam** [comment]
Great catch and agreed, verification support is very much work in progress as it has no UI yet, I will look to disable the feature whilst it's not ready :+1:

**Comment by ouchadam** [comment]
Fixed with https://github.com/ouchadam/chat-engine/pull/15 and included with https://github.com/ouchadam/small-talk/commit/339631dccda873bd1f1a38c7cf9ecba908d2a3d5
