### ISSUE TITLE
possibly intended behaviour ? back exits chat from notif

### ISSUE THREAD

**Issue by theotheroracle** [ouchadam/small-talk#269]
when you open a chat from a notification, and then press the back arrow ( either the system one or the one in the top left ) the app exits instead of returning to the chatlist . 

i would prefer the latter behaviour, so maybe this could be an option, as i could see this behaviour being wanted by some

**Comment by ouchadam** [comment]
:+1:  completely agree, pressing the back arrow should navigate "up" to the parent screen, which like you suggested would be the chat list

**Comment by theotheroracle** [comment]
just wanted to thank you for responding and fixing all these issues so quickly, this client is super promising

**Comment by theotheroracle** [comment]
( i would note that whilst the back arrow navigates correctly, system back still does not )
